# -*- coding: utf-8 -*-
"""source code for project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJZHXwipdSeHq_4Lis_Qb_Pyu58Sz_RT
"""

import tensorflow as tf
from tensorflow.keras import layers, models

# Input shape: (batch, height, width, channels), e.g., (None, 32, 128, 1)
input_img = layers.Input(shape=(32, 128, 1), name='input_image')

# CNN feature extractor
x = layers.Conv2D(64, (3,3), padding='same', activation='relu')(input_img)
x = layers.MaxPooling2D(pool_size=(2,2))(x)
x = layers.Conv2D(128, (3,3), padding='same', activation='relu')(x)
x = layers.MaxPooling2D(pool_size=(2,2))(x)
x = layers.Reshape(target_shape=(32, -1))(x)  # (batch, time_steps, features)

# BiLSTM layers
x = layers.Bidirectional(layers.LSTM(128, return_sequences=True))(x)
x = layers.Bidirectional(layers.LSTM(128, return_sequences=True))(x)

# Output layer for character probabilities
vocab_size = 80  # depends on your dataset (ASCII/Extended chars etc.)
x = layers.Dense(vocab_size + 1, activation='softmax')(x)

model = tf.keras.Model(inputs=input_img, outputs=x)
model.summary()